### PR TITLE
At startup tweets from mongodb loaded if they exist (updated)

### PR DESCRIPTION
**Pull request by scarlett950810**
update:
use pageID to get tweets from MongoDB and limit the result volume to 100 from MongoDB

### CODE REVIEW

**Comment by kangism** [comment]
@shubhamgoyal 

Trendspedia doesn't work... Try to log out first and see whether you can log in again.

Before I logged out, it seemed there were still no hot urls displayed in the system. 

Please remember to test the updates after making any revision. Thanks.

**Comment by allwinpb** [comment]
@kangism thanks for the catch!

This bug happened during the move to production configuration. Sorry I missed this bug since I was logged in at the time. I've created a pull request with the fix. The remote is already updated so it should be working for you now.

What do you mean "hot urls"?

**Comment by kangism** [comment]
@allwinpb Thanks Allwin for the prompt response.

Hot urls are those extracted from tweets and frequently mentioned in tweets. Even if two twitter users publish the same webpage url, the urls in each of their tweets are distinct. That is why we need to retrieve the web page content of each url in tweets. Then we can compare the web page contents of different urls and group same/similar web pages together. Finally we can pick up a representative url from each of the groups that contain a large number of urls as the hot urls. This is our ultimate goal.

But now we need to store the relevant info of each url in the database first. You can refer to the hot collection in mongodb to see what infomation should be stored in the database. For more details, you can ask @shubhamgoyal or me later. Thanks.

**Comment by allwinpb** [comment]
Ah, I believe this is in progress.
https://github.com/SeSaMe-NUS/Trendspedia2/pull/5 <-- Pull request adding functionality to crawl and summarize every URL found while searching through tweets. The summarization library we are using, https://github.com/bookieio/breadability still has issues with certain articles but works for most of the articles (This was one of the better ones I found).

They're yet to be displayed in any manner though, so please check back later!

**Comment by kangism** [comment]
great, thanks :)

**Pull request merged**
